AWSTemplateFormatVersion: '2010-09-09'
Description: Create a role with read-only access to CodeCommit, ECR, and S3.

Resources:
  rReadonlyCodecommitEcrS3Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AWSCodeCommitReadOnly

  rReadonlyCodecommitEcrS3InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
      - Ref: rReadonlyCodecommitEcrS3Role
    DependsOn:
      - rReadonlyCodecommitEcrS3Role

Outputs:
  oReadonlyCodecommitEcrS3Role:
    Value: !Ref rReadonlyCodecommitEcrS3Role
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", role ] ]
  oReadonlyCodecommitEcrS3InstanceProfile:
    Value: !Ref rReadonlyCodecommitEcrS3InstanceProfile
    Export:
      Name: !Join [ ":", [ !Ref "AWS::StackName", instance-profile ] ]
