AWSTemplateFormatVersion: '2010-09-09'
Description: Hosted Zone for EPT Applications

##################################
# This script creates an Route 53 Hosted Zone
##################################

Resources:
  rHostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: Hosted Zone for EPT Applications
      HostedZoneTags:
        - Key: Owner
          Value: davemm
      Name: app
      VPCs:
        - VPCId: !ImportValue app-01-vpc-stack:vpc-id
          VPCRegion: !ImportValue app-01-vpc-stack:vpc-region
  rDHCPOptions:
    Type: AWS::EC2::DHCPOptions
    Properties:
      DomainName: app
      DomainNameServers:
        - AmazonProvidedDNS
      Tags:
        - Key: Name
          Value: !Join [ ":", [ !Ref "AWS::StackName", dhcp-options ] ]
  rVPCDHCPOptionsAssociation:
    Type: AWS::EC2::VPCDHCPOptionsAssociation
    Properties:
      DhcpOptionsId: !Ref rDHCPOptions
      VpcId: !ImportValue app-01-vpc-stack:vpc-id
    DependsOn:
      - rDHCPOptions

Outputs:
    oHostedZone:
      Value: !Ref rHostedZone
      Export:
        Name: !Join [ ":", [ !Ref "AWS::StackName", hosted-zone ] ]
