AWSTemplateFormatVersion: 2010-09-09
Description: Example of starting an EC2 intance. Shows USERDATA use.

Parameters:
  pInstanceType:
    Description: "EC2 instance type"
    Type: String
    Default: t2.medium
  pAMI:
    Description: "CentOS AMI to use"
    Type: String
    Default: ami-6d1c2007
  pKeyname:
    Description: "PKI Key to use for SSH"
    Type: String
    Default: bogart-dmedinets

Resources:
  rLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      EbsOptimized: false
      IamInstanceProfile: arn:aws:iam::929717587211:instance-profile/app-aws-admin
      ImageId: !Ref pAMI
      InstanceMonitoring: false
      InstanceType: !Ref pInstanceType
      KeyName: !Ref pKeyname
      SecurityGroups:
        - !ImportValue app-03-security-groups-stack:world-incoming-ssh-sg
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash

          echo "Waiting for Network"
          until ping -w300 -c1 www.google.com &>/dev/null; do :; done

          yum update -y
          yum install -y curl git unzip yum-utils

          # Install Docker
          yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          yum makecache fast
          yum install -y docker-ce
          systemctl start docker
          systemctl enable docker
          usermod -aG docker centos
          echo "Docker Installed"

          curl https://s3.amazonaws.com/aws-cli/awscli-bundle.zip -o awscli-bundle.zip
          unzip awscli-bundle.zip
          ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
          rm awscli-bundle.zip
          echo "AWS CLI Installed"

          echo "Setting Credential Helper"
          su centos -c "git config --global credential.helper '!aws codecommit credential-helper \$@'"
          su centos -c "git config --global credential.UseHttpPath true"

          ###############################
          # place project specific commands here.
          ###############################

          touch /tmp/user-data-executed

  rAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      HealthCheckType: EC2
      LaunchConfigurationName: !Ref rLaunchConfiguration
      MaxSize: 1
      MinSize: 1
      Tags:
        - Key: Name
          Value: !Ref "AWS::StackName"
          PropagateAtLaunch: true
        - Key: ssh-user
          Value: centos
          PropagateAtLaunch: true
      VPCZoneIdentifier:
        - !ImportValue app-01-vpc-stack:public-subnet-a
        - !ImportValue app-01-vpc-stack:public-subnet-b
    DependsOn:
      - rLaunchConfiguration


Outputs:
  oLogLocation:
    Description: the location of the userdata script log
    Value: /var/log/cloud-init-output.log
